### ISSUE TITLE
bot wont start

### ISSUE THREAD

**Issue by belyy1337** [Zsunamy/HLTVDiscordBridge#12]
![image](https://user-images.githubusercontent.com/69053330/107735766-49d5dc00-6d22-11eb-95b2-f2faf139a91f.png)
help

**Comment by Drachenfalke12** [comment]
First of all you have to kick your bot from all your servers now. Then you can start the bot. For technical reasons the bot has to be online in order to join server properly. 
I'll try to fix that. Gonna keep you updated

**Comment by Drachenfalke12** [comment]
fixed with the new Update. You can now add the bot to a server even if it's offline
