### ISSUE TITLE
Can't Invite on My Server

### ISSUE THREAD

**Issue by rpkaul** [Zsunamy/HLTVDiscordBridge#49]
![image](https://user-images.githubusercontent.com/21355500/112791512-59657600-907f-11eb-8fb5-69bb72fb43bf.png)

**Comment by OfficialLahusa** [comment]
We are currently enqueued for the [discord bot verification routine](https://support.discord.com/hc/de/articles/360040720412-Bot-Verification-and-Data-Whitelisting), which we entered as soon as we reached a server count of 75. This state limits us to 100 servers before our bot and the api gateway intents we applied for get accepted officially. 
Thank you for your patience ^^
~ Lahusa

**Comment by Revilum** [comment]
bot is verified now so you should be able to add it to your server.
