### ISSUE TITLE
!live Not Returning Results

### ISSUE THREAD

**Issue by swiprCS** [Zsunamy/HLTVDiscordBridge#73]
Not really sure if this is because of the major (which is the entire reason I added the bot) but it looks like !live is returning nothing even though there are a solid number of live matches on /matches

**Comment by Revilum** [comment]
I can look into this issue tonight/tomorrow. We're currently working on a major rework of the bot so I'm not sure I'll be able to fix that

**Comment by swiprCS** [comment]
Not a big deal really for me. Just figured someone would probably also run into that :)

Thanks again!

**Comment by Revilum** [comment]
fixed with [fd92fb8](https://github.com/Zsunamy/HLTVDiscordBridge/commit/fd92fb83abae19bb8e3cdd64ab47bee3cc2e55cc). Haven't tested it yet with an actual live match but it should work now
