### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by arsalshahzaib** [Zsunamy/HLTVDiscordBridge#84]
i added the bot in my discord server and initialised it in a channel with the init command but still not getting any news updates in the server. can you please tell me the steps to properly set it up in a server?

**Comment by Revilum** [comment]
try readding the discord bot. there's also an issue where not all new messages get detected but I'm working on that to fix it.

**Comment by arsalshahzaib** [comment]
i did try it a load of times but no progress. The problem that you mentioned can be the issue with me but i am in another server that's not mine and there, the bot is perfectly working. Is there anything else that i have to do other than entering the the init command when i add it in my server?

**Comment by Revilum** [comment]
can you give me the server id of the broken server? Then I can look in the database and see if your configuration is missing

**Comment by arsalshahzaib** [comment]
it is working now. i don't know how but it's working. thanks anyway.
